# database configuration
DATABASE_URL = "sqlite:///proxies.db"
# list with proxy repos
github_repos_with_proxies = ['ALIILAPRO/Proxy/main/socks5.txt',
                             'Anonym0usWork1221/Free-Proxies/main/proxy_files/socks5_proxies.txt',
                             'B4RC0DE-TM/proxy-list/main/SOCKS5.txt',
                             'caliphdev/Proxy-List/master/socks5.txt',
                             'ErcinDedeoglu/proxies/main/proxies/socks5.txt',
                             'hookzof/socks5_list/master/proxy.txt',
                             'HyperBeats/proxy-list/main/socks5.txt',
                             'iptotal/free-proxy-list/master/socks5.txt',
                             'jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt',
                             'Zaeem20/FREE_PROXIES_LIST/master/socks5.txt',
                             'manuGMG/proxy-365/main/SOCKS5.txt',
                             'mmpx12/proxy-list/master/socks5.txt',
                             'MuRongPIG/Proxy-Master/main/socks5.txt',
                             'NotUnko/autoproxies/main/socks5.txt',
                             'officialputuid/KangProxy/KangProxy/socks5/socks5.txt',
                             'proxylist-to/proxy-list/main/socks5.txt',
                             'prxchk/proxy-list/main/socks5.txt',
                             'roosterkid/openproxylist/main/SOCKS5_RAW.txt',
                             'ShiftyTR/Proxy-List/master/socks5.txt',
                             'hsteamboatid/proxyout/main/proxy-socks5.txt',
                             'TheSpeedX/PROXY-List/master/socks5.txt',
                             'TylerAmesIsGay/proxy-list/main/socks5_proxies.txt',
                             'yemixzy/proxy-list/main/proxies/socks5.txt',
                             'Zaeem20/FREE_PROXIES_LIST/master/socks5.txt',
                             'zevtyardt/proxy-list/main/socks5.txt',
                             'zloi-user/hideip.me/main/socks5.txt',
                             'monosans/proxy-list/main/proxies/socks5.txt',
                             'monosans/proxy-list/main/proxies_anonymous/socks5.txt',
                             'monosans/proxy-list/main/proxies_geolocation/socks5.txt']
